### ISSUE TITLE
Read configuration from .csslintrc file

### ISSUE THREAD

**Issue by caiogondim** [SublimeLinter/SublimeLinter-csslint#1]
Is there a way already to do this?
Just like jshint reads the conf from .jshintrc?

**Comment by michaek** [comment]
@aparajita It appears that the `--config` option is [released](https://github.com/CSSLint/csslint/pull/502) on csslint. That should open the door to allowing SublimeLinter-csslint to detect and use a `.csslintrc` in the project root, right?

Unfortunately, when I try `--config` with csslint 1.0.4 I'm currently getting a type error, so it may not be as attainable at it seems from the docs...

**Comment by michaek** [comment]
It seems the CLI argument must use `=`, like `csslint --config=.csslintrc`. I do continue to get errors in the JSON syntax example [linked from the docs](https://github.com/CSSLint/csslint/wiki/Command-line-interface#configuration-files), but this .csslintrc format does work with 1.0.4:

```
--ignore=box-sizing,font-sizes
```
