### ISSUE TITLE
CSSLint - disable order-alphabetical warining in Sublime 3

### ISSUE THREAD

**Issue by ivvanov** [SublimeLinter/SublimeLinter-csslint#15]
Hello,

I searched trough the web, but I couldn`t find any info about how to disable the order-alphabetical warning in Sublime 3. There`s info only for Brackets. Can someone give me a step-by-step guide?

**Comment by Kristinita** [comment]
@ivvanov, `Preferences` → `Package Settings` → `SublimeLinter` → `Settings - User` → in opened file change

> "ignore": "",

to

> "ignore": ["order-alphabetical"],

Thanks.

**Comment by ivvanov** [comment]
Thanks :)

**Comment by Alecto** [comment]
"linters": {
            "csslint": {
                "@disable": false,
                "args": [],
                "errors": "",
                "excludes": [],
                "ignore": ["order-alphabetical"],
                "warnings": ""
            },

doesnt work, i still see warnings

**Comment by AlexYugra** [comment]
> 
> 
> ```
>     "linters": {
>         "csslint": {
>             "@disable": false,
>             "args": [],
>             "errors": "",
>             "excludes": [],
>             "ignore": ["order-alphabetical"],
>             "warnings": ""
>         },
> ```
> 
> doesnt work, i still see warnings

That's  great. But, could you hint how(where) to find out list of settigs to change? F.ex list of command csslint? And(important) list of command  html tidy I can add to ignore?
