### ISSUE TITLE
How to disable all warnings and leave only the error check?

### ISSUE THREAD

**Issue by Alecto** [SublimeLinter/SublimeLinter-csslint#17]
SublimeLinter-csslint shows warnings in all lines of code, although there are no errors.
http://image.prntscr.com/image/ec5d7379335547d297abe6fb050e9905.png
I read the wiki to turn off warnings, but I did not succeed.
https://github.com/CSSLint/csslint/wiki/Rules
http://image.prntscr.com/image/915df9a02ab44fa5b8916677ba1753dc.png
Help me plz to resolve my problem.

**Comment by IngAjVillalon** [comment]
Please I also wish that sublime will ignore the warnings, I searched in many parts and I did not find how to do it.
Help us please!

**Comment by greatkingrat** [comment]
`"warnings": "*"`

Disables warnings

**Comment by Flashwalker** [comment]
Since there is not a sufficiently informative explanation here, here it is:

Open the settings:
**Preferences > Package Settings > SublimeLinter > Settings**

So you can edit a file:
**~/.config/sublime-text-3/Packages/User/SublimeLinter.sublime-settings**

And add to "linters":
```
        "csslint": {
            "warnings": "*"
        },
```
Like this:
```diff
// SublimeLinter Settings - User
{
    // "debug": true,
    "delay": 0.0,
    "linters": {
        "quick-lint-js": {
            "executable": "/usr/bin/quick-lint-js"
        },
+        "csslint": {
+            "warnings": "*"
+        },
    }
}
```
