### ISSUE TITLE
shows error style and script tag in html file on sublime text 3

### ISSUE THREAD

**Issue by mohid108** [SublimeLinter/SublimeLinter-csslint#18]
i'm experiencing that kind of error for both style and script tag my ST3 version is 3143 
![script error](https://user-images.githubusercontent.com/29270685/35767994-cb75d522-091f-11e8-9d48-293bdd2f4f4d.PNG)
please solve my problem please help other wise i've to change my editor this is actually irritating me .

**Comment by braver** [comment]
Try the new versions of SublimeLinter and this plugin, should work much better.
