### ISSUE TITLE
Unknown property 'unicode-range'. (known-properties);

### ISSUE THREAD

**Issue by jtheletter** [SublimeLinter/SublimeLinter-csslint#19]
Why should this warning throw? 

`Unknown property 'unicode-range'. (known-properties);`

Documentation: 
- https://caniuse.com/#search=unicode-range
- https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range

How can I add `unicode-range` to `known-properties` (I don't see instruction on https://github.com/CSSLint/csslint/wiki/Require-use-of-known-properties).

**Comment by jaepage** [comment]
Update: I found in [this GitHub issue thread](https://github.com/SublimeLinter/SublimeLinter-csslint/issues/10#issuecomment-106937352) how `ignore_match` can disable this failed known property (not quite adding to known properties, but effectively so).

**Comment by braver** [comment]
Better ask around over at the CSSLint repo. They provide the configuration options, SublimeLinter doesn't do anything here. I bet they have config file you can edit.
