### ISSUE TITLE
Style attribute errors

### ISSUE THREAD

**Issue by willrowe** [SublimeLinter/SublimeLinter-csslint#22]
I started getting the following linter error today in HTML style attributes:

```
Expected a `FUNCTION` or `IDENT` after colon at line x, col x.
```

It seems to be caused by setting the `selector` to `source.css`. I'm not sure if `csslint` is able to lint style attributes or not, so that may be the issue.

**Comment by kaste** [comment]
Oh 💩 . @braver 🆘

**Comment by braver** [comment]
🚒

**Comment by willrowe** [comment]
Thank you, I can confirm it fixes the issue.
