### ISSUE TITLE
working directory of the plugin needed to place .csslintrc

### ISSUE THREAD

**Issue by chrisgrieser** [SublimeLinter/SublimeLinter-csslint#25]
I am following the [instructions at the csslint documentation](https://github.com/CSSLint/csslint/wiki/Command-line-interface#configuration-files) and set up my `.csslintrc` configuration file. However, the file is only considered by csslint, when there is located in the working directory. With the CLI, this is easily done, but where is the working directory of the SublimeLinter-csslint-plugin? 

It does not seem to be my home directory `~/` or any other Sublime-related path I tried out.  There is no information in the documentation where to place `.csslintrc`?

**Comment by kaste** [comment]
Howdy, old issue.  The `cwd` is *usually* one of the top folders you can see in the sidebar.  For example, if you do `subl .` on the command line, whatever the `.` refers to should become your working dir.  

You *can* override the working dir in the settings, also per project in the project settings.
