### ISSUE TITLE
Plugin linting html style tag and forcing errors.

### ISSUE THREAD

**Issue by Jonas-Degn** [SublimeLinter/SublimeLinter-csslint#6]
"This linter plugin for SublimeLinter provides an interface to csslint. It will be used with files that have the 'CSS' syntax, or within style tags in HTML files"
The plugin doesn't only lint the CSS inside the style tag, but also the style tag itself, causing some errors.

An empty style tag only throws one error, trimming empty, which is fine.

But a not empty style tag
<pre>&lt;style type="text/css"&gt;
 /\* some actual css */
&lt;/style&gt;</pre> throws 9 errors: 
Unexpected token '<' at line 1, col 1;
Expected LBRACE at line 1, col 12;
Unexpected token '=' at line 1, col 12;
Unexpected token '"text/css"' at line 1, col 13;
Unexpected token '>' at line 1, col 23;
Unexpected token '<' at line 3, col 1;
Unexpected token '/' at line 3, col 2;
Unexpected token 'null' at line 4, col 1;
Unexpected token 'null' at line 4, col 1;

![image](https://cloud.githubusercontent.com/assets/5509086/3870557/8465a766-20d4-11e4-9623-6dc213d5e64c.png)

**Comment by sekai92id** [comment]
Actually you can change the Syntax from HTML to HTML (Angular.js). You can change to HTML (Angular.js) after you installing AngularJS Snippet from Package Control and no more error
